dealer:
    path:     /
    defaults: { _controller: "OmarSiteBundle:Dealer:index" }

dealer_show:
    path:     /{id}/show
    defaults: { _controller: "OmarSiteBundle:Dealer:show" }

dealer_new:
    path:     /new
    defaults: { _controller: "OmarSiteBundle:Dealer:new" }

dealer_create:
    path:     /create
    defaults: { _controller: "OmarSiteBundle:Dealer:create" }
    requirements: { _method: post }

dealer_edit:
    path:     /{id}/edit
    defaults: { _controller: "OmarSiteBundle:Dealer:edit" }

dealer_update:
    path:     /{id}/update
    defaults: { _controller: "OmarSiteBundle:Dealer:update" }
    requirements: { _method: post|put }

dealer_delete:
    path:     /{id}/delete
    defaults: { _controller: "OmarSiteBundle:Dealer:delete" }