omar_site_homepage:
    path:     /
    defaults: { _controller: OmarSiteBundle:Default:index }
    
OmarSiteBundle_dealer:
        resource: "@OmarSiteBundle/Resources/config/routing/dealer.yml"
        prefix:   /dealer

OmarSiteBundle_avatar:
        resource: "@OmarSiteBundle/Resources/config/routing/avatar.yml"
        prefix:   /avatar
