parameters:
#    omar_site.example.class: Omar\SiteBundle\Example

services:
#    omar_site.example:
#        class: %omar_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
